[base]
name = pygenstability
files = src/{[base]name}

[tox]
envlist =
    lint
    py{310,311,312}
    coverage
    docs

[testenv]
setenv =
    COVERAGE_FILE = {env:COVERAGE_FILE:.coverage-{envname}}
deps = pybind11
extras = all
commands = pytest -s \
    --basetemp={envtmpdir} \
    --cov={[base]name} \
    --no-cov-on-fail \
    --cov-report term-missing \
    --cov-fail-under=100

allowlist_externals = make

[testenv:coverage]
skip_install = true
deps = coverage
allowlist_externals = /bin/bash
commands =
    /bin/bash -c 'coverage combine .coverage-py*'
    coverage xml
    coverage report

[testenv:lint]
basepython = python3
skip_install = true
deps =
    ruff

commands =
    ruff check {[base]files}
    ruff format --check {[base]files}

[testenv:format]
skip_install = true
deps =
    ruff
commands =
    ruff check --fix {[base]files}
    ruff format {[base]files}

[testenv:docs]
extras = all
changedir = docs
deps = 
    pybind11
    sphinx
    sphinx_click
    sphinx_mdinclude
    furo 
    nbsphinx
    pandoc
    ipython

whitelist_externals = make
commands =
    make clean
    make html

[gh-actions]
python =
  3.10: py310, lint, docs, coverage
  3.11: py311
  3.12: py312
